export const lexiconData = [
  {
    Names: ["Ava", "Alfred", "Sam", "Ewan", "Ansel", "Ruth", "Hazel"],
  },
  {
    monadicPredicates: [
      "[1] studies",
      "[1] concentrates",
      "[1] sits",
      "[1] climbs",
      "[1] will pass",
      "[1] will run",
      "[1] will walk",
      "[1] will stand",
      "[1] will bite",
      "[1] drank",
      "[1] ate",
      "[1] sang",
      "[1] swam",
      "[1] is mean",
      "[1] is happy",
      "[1] is mortal",
      "[1] is honest",
      "[1] is sad",
      "[1] is wet",
      "[1] is guilty",
      "[1] is round",
      "[1] is square",
      "[1] is an elf",
      "[1] is a human",
      "[1] is a knight",
      "[1] is a knave",
      "[1] is a monkey",
      "[1] is a student",
      "[1] is a person",
      "[1] is a teacher",
      "[1] is a number",
    ],
  },

  {
    binaryPredicates: [
      "[1] loves [2]",
      "[1] admires [2]",
      "[1] sees [2]",
      "[1] kissed [2]",
      "[1] talked to [2]",
      "[1] waved to [2]",
      "[1] is less than [2]",
      "[1] is greater than [2]",
      "[1] is a successor of [2]",
    ],
  },
];
