export const lexiconDataProp = [
  {
    Propositions: [
      "Sam studies",
      "Ava sang",
      "Ava ate",
      "Alfred is a knight",
      "Ava will stand",
      "Emily sits",
      "Ava studies",
      "Ava will pass",
      "Sam is a knight",
      "Sam is honest",
      "Sam is a knight",
      "Sam is honest",
      "Sam is a knave",
      "Sam is honest",
      "Sam is a knave",
      "Sam is a knight",
      "Ava will pass",
      "Ava concentrates",
      "Ava is happy",
      "Ava will pass",
      "Ava drank",
      "Ava will pass",
      "Ava drank",
      "Ava is happy",
      "Sam sang",
      "Sam will stand",
      "Ava sits",
      "Ruth is happy",
      "Ansel will bite",
      "Ansel is sad",
      "Ansel will bite",
      "Sam sits",
      "Sam is honest",
      "Sam is a human",
      "Sam is mortal",
      "Alfred is wet",
      "Alfred swam",
      "Ruth sang",
      "Ruth swam",
      "Ava waved to Sam",
      "Sam waved to Ava",
      "Alfred waved to Emily",
      "Emily is sad",
      "Sam is a knight",
      "Sam is honest",
      "Alfred will walk",
      "Ruth will walk",
      "Ava will run",
      "Sam will run",
      "Alfred studies",
      "Alfred will pass",
      "Alfred concentrates",
      "Sam sits",
      "Ava sits",
      "Ruth will stand",
      "Alfred will stand",
      "Ruth will stand",
      "Sam will stand",
      "Ava is happy",
      "Sam is happy",
      "Ruth studies",
      "Ruth will pass",
      "Sam is happy",
      "Sam will pass",
      "Sam is a knave",
      "Sam is honest",
      "Ava will pass",
      "Ava studies",
      "Sam is an elf",
      "Ansel is an elf",
      "Emily drank",
      "Emily sang",
      "Alfred swam",
      "Sam swam",
      "Ansel is mean",
      "Ansel is an elf",
      "Ansel will bite",
      "Ruth swam",
      "Ruth talked to Alfred",
      "Alfred is guilty",
      "Sam is happy",
      "Sam ate",
      "Sam drank",
      "Ruth admires Ava",
      "Ruth admires Emily",
      "Ruth admires Ruth",
      "Sam is honest",
      "Sam is a person",
      "Sam will stand",
      "Ava kissed Sam",
      "Ruth kissed Sam",
      "Alfred talked to Ruth",
      "Sam talked to Ruth",
      "Ava will pass",
      "Sam studies",
      "Emily studies",
      "Ava will pass",
      "Sam will pass",
      "Emily will pass",
      "Sam will run",
      "Sam will walk",
      "Sam will stand",
      "Sam is honest",
      "Sam is a person",
      "Sam is happy",
      "Sam drank",
      "Ava drank",
      "Alfred is wet",
      "Alfred swam",
      "Emily talked to Sam",
      "Ruth talked to Sam",
      "Emily talked to Sam",
      "Ruth talked to Sam",
      "Alfred kissed Ruth",
      "Alfred sang",
      "Alfred drank",
      "Ava drank",
      "Ava sang",
      "Ruth will run",
      "Ava will run",
      "Sam is a monkey",
      "Sam will bite",
      "Sam is mean",
      "Alfred is honest",
      "Ruth loves Alfred",
      "Ava is sad",
      "Ava is wet",
      "Ava is guilty",
      "Ava climbs",
      "Ava sits",
      "Ava concentrates",
      "Ava will run",
      "Sam will run",
      "Emily will walk",
      "Ruth will walk",
      "Alfred talked to Ruth",
      "Alfred sang",
      "Alfred will pass",
      "Ava will stand",
      "Ruth will stand",
      "Alfred will run",
      "Sam will run",
      "Ava will run",
      "Emily will run",
      "Ruth will run",
      "Sam will stand",
      "Sam will walk",
      "Ava ate",
      "Sam ate",
      "Ruth ate",
      "Alfred ate",
      "Alfred will run",
      "Alfred ate",
      "Alfred is a teacher",
      "Alfred is mean",
      "Sam sits",
      "Alfred sits",
      "Emily sits",
      "Sam will run",
      "Alfred will run",
      "Emily will run",
      "Ava talked to Ruth",
      "Ruth swam",
      "Ava swam",
    ],
  },
];
